### ISSUE TITLE
Identifikace a tabulka rizik

### ISSUE THREAD

**Issue by hejdujir** [Spravce-Ukolu-Tym/Spravce-ukolu#13]

**Comment by michato4** [comment]
Pište mi návrhy...:-)

**Comment by hejdujir** [comment]
Tak už jsem vypracoval předběžný návrh rizik...:-) Koukněte na to...:-)

**Comment by soucemi** [comment]
Zařízení, ne Zazíření. Krom tohodle preklepu me toho nenapada vice.

**Comment by soucemi** [comment]
Tak jediny technologicky problemy muze bejt neznalost myqsl <-> java (s tim bude poblem malej) a trosku horsi muze bejt to JRMI....Vic zasadnejsich problemu by imho byt nemelo, leda ze byste nebyli schopni ani tech zakladu... to snad ale budete...
