### ISSUE TITLE
Kritika POS

### ISSUE THREAD

**Issue by michato4** [Spravce-Ukolu-Tym/Spravce-ukolu#16]

**Comment by michato4** [comment]
tak jsem zatím napsal nějakej "nástřel" oponentury k furps (viz commit).. chce to ještě zvážit a doplnit o pozitivní kritiku k čemuž se ještě snad do večera dostanu. Bylo by dobré kdyby někdo zkouknul ještě ten POS jako takový a něco k tomu napsal, jeslti se tu ještě dnes někdo octnete..  pak to dáme do jednoho dokumentu

**Comment by hejdujir** [comment]
Hele, dávám sem také dokumet ohledně pos a všech poznatků, shlédni to... :-)

**Comment by michato4** [comment]
supr, prolít sem to, upravil pár překlepů a doplnil to tím mým.. :-)
