### ISSUE TITLE
Instalace SW na server, zaplaceni SMS

### ISSUE THREAD

**Issue by soucemi** [Spravce-Ukolu-Tym/Spravce-ukolu#21]
Taaaaak, a kdopak se obetuje? Server by byl, jen je potreba poslat tu SMS:

Pošlete SMS ve tvaru: pm pipni 81834
Pro ČR (v síti o2, T-Mobile a Vodafone) na číslo 9033330 Cena SMS je 30,00 Kč s DPH
Pro SR na číslo 6676 Cena SMS je 1,205 Eur s DPH
Technicky zajišťuje Airtoy a.s. Reklamace plateb na reklamace@airtoy.cz nebo na lince 602 777 555, 9-17 hodin, po-pá, www.platmobilem.cz. Kontakt na provozovatele: vserver@vserver.cz.

Az to nekdo udela, dejte vedet :D 

Pak je potreba nainstalovat SW:
Java
MySQL

je tam debian. Prihlasovaci udaje zaslu, OSS snad mate vseci tak si to aspon vyzkousite na realnym.

**Comment by hejdujir** [comment]
Jasně, pošlu to... :-)

**Comment by hejdujir** [comment]
odesláno... :-)
