### ISSUE TITLE
Vytvoreni DB

### ISSUE THREAD

**Issue by soucemi** [Spravce-Ukolu-Tym/Spravce-ukolu#22]
Az bude zprovoznenej server a nakonfena MySQL, tak klidne nejakejma klikackama vytvorit DB. Schema mate jako ten DB model. V MyISAM myslim ani netreba resit cizi klice, takze to bude prace asi opravdu na chvilu.

**Comment by michato4** [comment]
naklikal jsem to a vyexportoval jako prikaz sql, takze az bude server pristupnej, tak se to tam muze importovat..
