### ISSUE TITLE
Rozpočet

### ISSUE THREAD

**Issue by hejdujir** [Spravce-Ukolu-Tym/Spravce-ukolu#24]
Toto bylo v aktualitách, mohl by jsi to  tam nějak zahrnout, jak jsi na ty čísla přišel??

"Při sestavování rozpočtu projektu vysvětlujte, kde jste získali čísla se kterými operujete"

:-)

**Comment by michato4** [comment]
tak jsem to tam dopsal ještě do poznámky. myslím, že to musí být jasné..
