### ISSUE TITLE
Potřeba k analýze

### ISSUE THREAD

**Issue by hejdujir** [Spravce-Ukolu-Tym/Spravce-ukolu#25]
platforma/frameworky 
 popis balíčků 
 popis rozhraní tříd 

 Součástí hodnocení návrhu je i hodnocení kvality zdrojového kódu. Po dohodě se cvičícím mohou být některé části zpracovány pomocí vhodného nástroje - např. JavaDoc.

**Comment by soucemi** [comment]
Jak moc do detailu teda vsecko chces? 

Jede to na Jave, vyuziva Java RMI. Popis rozhrani snad zvladnes vymyslet sam (predpokladam ze jde o popis funkcnosti)....

**Comment by michato4** [comment]
přidám ještě to co nám k tomu říkal na cvičení:

-v jednom pdf
-požadavky
-use case
-analytický model tříd
-návrh - hlavní třídy, návrhový model tříd co už jsou jasné + popis tříd na úrovni server-client

**Comment by hejdujir** [comment]
to soucemi: no tak balíčky bys napsat mohl... :-D
platforma a frameworky taky.. :-D

**Comment by hejdujir** [comment]
Už jsem to jaksi dal trochu dohromady, tak na to kouknete, zda to tak muze byt... .
