### ISSUE TITLE
Kritika k POS a FURPS

### ISSUE THREAD

**Issue by hejdujir** [Spravce-Ukolu-Tym/Spravce-ukolu#3]
Měli bychom se domluvit na nějaké úpravě těchto dokumentů a mít nějakou zpětnou odezvu odevšech členů :-)

**Comment by coav** [comment]
Tak jsem si to všechno pečlivě přečetl a fakt smekám - shrnul jsi to fakt výborně a nenašel jsem tam v podstatě nic dalšího, co bych dopsal...

Jen pár malých drobností:

1) Overview - "a dle náročnosti a priority úkolu i zaměstnance zkušeného"
- tahle věta by chtěla nějak přeformulovat, nějak to nedává smysl :-) 

3) Success Criteria - "aby vše stih" - jen malej překlep L na konci

5) Critical Factors - Špatná komunikace - 30% je málo - myslim si, že aspoň 50-70%
- komunikace nám celkem vázne :-(
