### ISSUE TITLE
Odevzdání - PIŠTE ČASY, KDY VÁM VYHOVUJE

### ISSUE THREAD

**Issue by michato4** [Spravce-Ukolu-Tym/Spravce-ukolu#32]
Během tohoto týdne je nutné vše dokončit a připravit projekt k odevzdání. Je nutné, abychom se se cvičícím sešli všichni najednou a to v úterý nebo středu, přičemž jsou cvičícím preferovány dopolední časy. <b>Do commentů napište, jaké časy byste preferovali</b> vy a pak se z toho něco snad dá dohromady.

**Comment by michato4** [comment]
moje časy dle preferencí sestupně:
st - snad kdykoliv od 11:00
út - snad kdykoliv od 11:00

před 11:00 horší, ale nouzově i tak..

**Comment by hejdujir** [comment]
Jsem pro ve středu okolo té 11:00. Teď ještě zda je to tato středa, nebo příští? :-D No a kde se sejdem...? :-D

**Comment by michato4** [comment]
no měl jsem zato že ta příští, ale teď tedy nevím :D.. každopádně do téhle středy to stejně vidím na dokončení nereálně

**Comment by soucemi** [comment]
Do zitra udelame prd uz jen proto, ze jeste musim udelat prezentacku na OSS a pripravit se na prezentacku na MPS... predpokladam tudiz prespristi stredu... skolu mam do 9:00, takze kdykoliv potom (jen abych se stih' dopravit na KN)

**Comment by coav** [comment]
Mně taky vyhovuje středa v podstatě kdykoliv :-)

**Comment by soucemi** [comment]
Héle, co vlastne od nas teda bude vsechno ocekavat, co ocekavate vy odeme ze jeste urobim? Testy skoro nevim jak napsat (strasne blbe se to testuje, protoze do DB jde nacpat vicemene vsecko a testovat co dostanu z DB se mi nelibi, protoze pak zalezi na konkretni DB, k ktery se pripojim)....

**Comment by michato4** [comment]
do issue klient jsem ti teď psal ještě poznámku k tomu konzolovýmu klientovy (potažmo možná se to týká i serveru), jestli nevis kde bude chyba.. ale jinak tedy, jeslti už je ten server hotov, tak už snad je odstranime ty mock objekty a ideálně nevznikne další problém..

co se týče testů, tak jsem tedy také moc nevěděl co s tím, ale nakonec jsem dospěl (jak jsem si teď přečetl) snad k něčemu podobnému jako má druhý tým - úryvek z jejich práce: "Znamená to, že testy se nebudou snažit ozkoušet všechny kombinace vstupních a výstupních hodnot. Uživatelské rozhraní se nebude testovat. Bude se vesměs jednat o blackbox testy na úrovni veřejných metod tříd.". Tak snad to postačí.. 

takže nyní to ještě nějak dopracuju, abychom jim to mohli konečně poslat na oponenturu a někdo by měl asi domluvit se cvičícím ten termín.

**Comment by michato4** [comment]
zápočtová konzultace se tedy uskuteční ve středu v 11:00 v KN:E-429
(psal jsem vám to mailem, ale pro jistotu to dávám i sem)
