### ISSUE TITLE
Analýza a návrh

### ISSUE THREAD

**Issue by hejdujir** [Spravce-Ukolu-Tym/Spravce-ukolu#4]
požadavky 
 scénáře užití 
 doménový model 
 business process model 
 platforma/frameworky 
 popis balíčků 
 popis rozhraní tříd 

 Součástí hodnocení návrhu je i hodnocení kvality zdrojového kódu. Po dohodě se cvičícím mohou být některé části zpracovány pomocí vhodného nástroje - např. JavaDoc.

**Comment by michato4** [comment]
musíme si uvědomit, že máme skluz s přípravami na cvičení.. takže do příště musíme krom přehledu požadavků a případů užití sestavit také analytický model tříd (myslím, že je to jiný název pro doménový model) a WBS (http://en.wikipedia.org/wiki/Work_breakdown_structure). Na to bych se tedy zaměřil především..

Je nás na to 6. Dobré by tedy bylo, kdyby si každý ze seznamu v zadání tohoto issue něco vybral, svůj výběr sem napsal a co nejdříve zpracoval, ať máme případně čas na doladění a čtvrteční zkonzultování po SPS. Při zpracování můžete vycházet ze slidů z přednášek + z internetu, kde k tomu vždycky určitě něco najdete..

Já tedy začnu těmi požadavky (ty je zřejmě nutné mít před zpracováním WBS)..

**Comment by hejdujir** [comment]
Tak já budu s Tomem dělat na BWS, USECASE a dál udělám rozdělení bodů na wiki a zpracuju výpisy práce + kouknu na doménový model a požadavky a dodělám to POS... :-)

**Comment by hejdujir** [comment]
Dále bych chtěl na Vás apelovat s tím, že by nebylo od věci, aby se každý zapojil.... Nic mi není do Vašeho soukromí a nevím kolik kdo máte času, ale na to, že každý den strávím 3 hodiny cestováním, tak toho odvádím celkem dost... A to, díky Vaší nečinosti, zanedbávám v úterý přednášky...:-( Takže už nevím, jak Vás mám s Tomem motivovat k nějaké činnosti, ale bylo by opravdu fajn, kdyby jsem každý napsal, beru si na starost to a to, mám námitek k tomu a k tomu, změníme to a to... A né, že to zustane na nás s Tomášem..:-(

**Comment by hejdujir** [comment]
Dotázek: Je pravda, že Doménový model = konceptuální model = use case??? Když, našel jsem toto:

"Doménový model poskytuje strukturální pohled na doménu, která může být doplněna o další dynamické pohledy, jako je například Use Case model."

a toto

"Doménový model v řešení problémů a softwarového inženýrství může být myšlen jako konceptuální model"

**Comment by michato4** [comment]
podle toho bych si myslel, že doménový model = konceptuální, ale use case už k rovnosti nepatří..

**Comment by michato4** [comment]
asi chyba domluvy, ale nahrál jsem do repozitáře i moji verzi modelu požadavků.. úplně nevim jakym to ma byt stylem, ale případně se teda zahodí.. večer ještě kouknu na vše co přibylo ať mám přehled a případně dám dál vědět do čeho bych se pustil

**Comment by michato4** [comment]
tak jsem to zkoukl a co se týče toho usecase, tak nemám námitky, ten model procesů je taktéž supr, jen by to chtělo opravit nějaký překlepy co tam jsou, ale někde jsem četl, že to bude Jirka překreslovat v yEd, takže tam se to asi vyřeší :-)

**Comment by hejdujir** [comment]
Kdepak jsou překlepy??? :-D Jo a  snad to Michal předělá... :-)

**Comment by michato4** [comment]
no spíš teda někde chybí písmenka :-D..: Hodnocení prác(e), Hodnoti(t) pracovníky
