### ISSUE TITLE
Nazvy souboru, diakritika, kodovani

### ISSUE THREAD

**Issue by soucemi** [Spravce-Ukolu-Tym/Spravce-ukolu#5]
Tak jsem konecne na to vlitnul. Snad se obcas dokopu k tomu neco delat, zatim jsem udelal ten graf atd. Sorry za ty nesmysly u ty zpravy k commitu, ale nez jsem zvladnul ukoncit ten vim, tak jsem tam nahazel dost nesmyslu. No, ale k veci:

Zkuste se vyvarovat diakritiky v nazvech souboru (ackoliv bych cekal, ze v dobe kdy utf-8 je bezny, furt bejva problem) a idealne i mezer a jelikoz to cely bezi na linuxu (github), piste pro jistotu vsecko s malejma pismenkama. Diky....

(jo, a ty docx, xls a podobne mi libreoffice (ex. openoffice.org) vubec neni schopno otevrit).

**Comment by hejdujir** [comment]
jen tomu graphML, kde a jak to otevřít a jak s tím pracovat? Ten rosypanej čaj mi moc neřekl... :-D

**Comment by soucemi** [comment]
To je prosim XMLko, zaklad vseho 8-). Psal jsem to v commit-commentu. yEd - http://www.yworks.com/en/products_yed_about.html

**Comment by hejdujir** [comment]
Paráda, tak když Ti to tak jde, tak se mrkni na ten Model Procesů, zda tam něco chybí a kdyžtak se to předělá v tom yEd... :-) Pač ten Use Case mi příjde fajne...-)

**Comment by hejdujir** [comment]
Jo a jde to nějak uloži jako normální obrázek?? Pač bych to chtěl vystavit na wiki...:-)

**Comment by hejdujir** [comment]
Tak už jsem na to přišel... :-D
