### ISSUE TITLE
Práce na víkend

### ISSUE THREAD

**Issue by hejdujir** [Spravce-Ukolu-Tym/Spravce-ukolu#7]
Tak zde je rozpis práce na víken...

Já - srovnám požadavky a předělám podle nich POS, FURPS, Use CASE, Požadavky, a vše, kde se vyskytují...
Tomáš - WBS + potřeboval bych menší nápad na GUI
Michal Souček - Jelikož jsi takový nejzběhlejší v programování, potřebovali bychom od Tebe Analytický model tříd, vypadá to takto: http://www.fi.muni.cz/~buhnova/PV167/07_Studium_ClassAnalyza.jpg + ještě návrh na platforma/frameworky

A od ostatních potřebuji: scénáře užití, plus nárhy a kritiku...

**Comment by hejdujir** [comment]
Plus, zapoměl jsem se zeptat, myslíte, že JOBS bude mít dotikový náhrobek??? :-D

**Comment by hejdujir** [comment]
Dokončené požadavky, kterých se budeme držet a upravený Use Case, dodělám to i na wiki... :-) Řiďte se dle požadavku...:-)

**Comment by hejdujir** [comment]
Tak požadavky už jsou kompletně hotové, ještě upravím Model procesů a vrhnu se na GUI

**Comment by coav** [comment]
Začal jsem dělat nějaké ty scénáře užití, akorát pořádně nevim co si pod tím představit :-) 
Tak to kdyžtak skoukněte a řekněte nějaké nápady...

**Comment by hejdujir** [comment]
to COAV: Koukni se na toto:
http://formular-ekf.vsb.cz/formulare/F01/tsw/getfile.php?prispevekid=872
http://uml.czweb.org/pripad_uziti.htm

Myslím, že tam by se to vyhledat dalo...:-)
