### ISSUE TITLE
BWS

### ISSUE THREAD

**Issue by hejdujir** [Spravce-Ukolu-Tym/Spravce-ukolu#8]
Kouknout na to BWS, pokud k tomu byly nějaké připomínky... :-)

**Comment by michato4** [comment]
udělal jsem tedy tu verzi, kde se projekt člení podle činností nutných pro realizaci jednotlivých vlastností (držel jsem se snad striktně našich požadavků) a tak ho může zachytit i po chronologické stránce.. :-)
připsal jsem tam i odhady trvání, ale jelikož nemám zas takové zkušenosti a nevím jaké jsou vaše, tak nemusí moc odpovídat realitě - možná by se hodilo provést nějaký ten časový poker. možnost připomínek je samozřejmostí ;-), tyhle věci určitě každý vidí jinak

**Comment by hejdujir** [comment]
Tak tedy, mně osobně se to zdá dost dobrý a uvidíme, co nám k tomu poví on... :-) Považuj to za hotové... :-D
