### ISSUE TITLE
Model tříd

### ISSUE THREAD

**Issue by hejdujir** [Spravce-Ukolu-Tym/Spravce-ukolu#9]
Předělat ten model tříd, jak bylo na tabuli, ale nechat i ten strarý...:-)

**Comment by coav** [comment]
Mám vyfocenou tu tabuli, ale nemůžu přijít na to, jak sem uploadnout obrázek :-D

**Comment by hejdujir** [comment]
Tak mi ho poli...:-)

Dne uivatel coav  
reply@reply.github.com  
napsal:

**Comment by coav** [comment]
Tady je :-)

2011/10/11 Hejdujir <
reply@reply.github.com>

**Comment by hejdujir** [comment]
Jen tak na okraj, nějak se mi ten obrázek neposlal... :-D

**Comment by coav** [comment]
Coe??? Vdy ho mm v odeslan ploze :-) tak znova :-D

Dne 12. jna 2011 7:26 Hejdujir <
reply@reply.github.com>napsal(a):

**Comment by hejdujir** [comment]
Hele, musíš to pořád posílat přes GITHUB?? :-D Pořád na Gmailu nemám přílohu... :-D

**Comment by hejdujir** [comment]
Tak jsem Ti Michale nahral na GITHUB tu fotku te tabule...:-)

**Comment by soucemi** [comment]
Tak jsem to nejak udelal. Jelikoz commit-msg nikdo necte, tak jeste jednou to napisu sem: prosim, kouknete na to a zkuste to pripadne nejak zkritizovat. Tu stranku kam jsem si to psal jsem nekde nechal a samozrejme zapomnel... 

Nekdy behem zitrka/pozitrka se vrhnu na implementaci....

je to ten classmod a dbmod. Diky...

**Comment by hejdujir** [comment]
Hele, tak me se to zda v pohode, hlavne mam radost, ze uz se to nejak hejbe:-D Jinak, napis mi straveny cas a ja Ti ho dopisu... :-) Jo a ja prosim o kritiku rizik... :-)
